package com.chatop.api.exceptions;

public enum ApiCodeEnum {
    NOT_FOUND,
    UNAUTHORIZED,
    AUTHENTICATION_FAILED,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR,
    BAD_REQUEST,
    USER_CONFLICT,
    TOKEN_VALIDATION_FAILED,
    TOKEN_EXPIRED,
    DATABASE_ERROR,
    CREATION_ERROR,
    TOKEN_ERROR,
    UPLOAD_ERROR
}
